### PR TITLE
Bug: missing np in log of non-wiggle Eisenstein-Hu

### PR DESCRIPTION
**Pull request by santiagocasas**
Solves issue #34 

image

### CODE REVIEW

**Comment by EiffL** [comment]
Oh wow! thanks for catching that!

**Comment by EiffL** [comment]
Feel free to merge :-D

**Comment by EiffL** [comment]
@all-contributors please add @santiagocasas for bug and code

**Comment by santiagocasas** [comment]
> Oh wow! thanks for catching that!

thanks, another thing I needed for GCspectro, otherwise I would have never seen it of course, hehe.

However, I can't merge, I don't have the rights.

**Comment by EiffL** [comment]
lol, oups, let me do it this time then

**Pull request merged**
