### PR TITLE
Spline interpolation

### PR DESCRIPTION
**Pull request by austinpeel**
First attempt at a JAX implementation of scipy's InterpolatedUnivariateSpline.

### CODE REVIEW

**Comment by EiffL** [comment]
Awesome !!! Thanks @austinpeel I'll try that out ASAP!

**Comment by EiffL** [comment]
image
Yes \o/ perfect agreement with scipy confirmed :-D

**Comment by EiffL** [comment]
Interpolation for growth, achieves better accuracy with only 32 points compared to 128 with linear interpolation \o/

**Comment by EiffL** [comment]
I've added my fix to the quadratic interpolation, we are now matching SciPy to machine precision on linear, quadratic, and cubic interpolation \o/ 
I've also added a few tests to make sure we don't break this in the future ^^'

Other things I did, I made the Spline object interpretable by JAX with these flatten and unflatten methods, so that it can be backpropagated against, and also passed as argument to jitted function :-D
Also, remove the explicit jit calls, as I think (if I understand the JAX philosophy correctly), it should be left to the user to decide what and when to jit.

Please have a look and in the meantime, I'm gonna mark this PR ready for review.

**Comment by EiffL** [comment]
AAAAAnnnnnnd Now that we have splines, we can integrate them exactly :-) And that makes me very happy :-D

**Comment by austinpeel** [comment]
Excellent! We can even integrate now :)
I think this all looks good.

**Pull request merged**
